### ISSUE TITLE
SyntaxError: invalid syntax in read_ole_fields.py

### ISSUE THREAD

**Issue by nikhilh-20** [kirk-sayre-work/ViperMonkey#16]
I'm getting a syntax error in `read_ole_fields.py` right after installing ViperMonkey.

Steps to reproduce:
```
root@malnet:~# pip install -U https://github.com/kirk-sayre-work/ViperMonkey/archive/master.zip
Collecting https://github.com/kirk-sayre-work/ViperMonkey/archive/master.zip
  Downloading https://github.com/kirk-sayre-work/ViperMonkey/archive/master.zip
     - 870kB 13.8MB/s
Requirement already satisfied, skipping upgrade: colorama in /usr/local/lib/python2.7/dist-packages (from vipermonkey==0.8) (0.4.1)
Requirement already satisfied, skipping upgrade: colorlog in /usr/local/lib/python2.7/dist-packages (from vipermonkey==0.8) (4.0.2)
Requirement already satisfied, skipping upgrade: olefile in /usr/local/lib/python2.7/dist-packages (from vipermonkey==0.8) (0.46)
Requirement already satisfied, skipping upgrade: oletools in /usr/local/lib/python2.7/dist-packages (from vipermonkey==0.8) (0.54.2)
Requirement already satisfied, skipping upgrade: prettytable in /usr/local/lib/python2.7/dist-packages (from vipermonkey==0.8) (0.7.2)
Requirement already satisfied, skipping upgrade: pyparsing==2.3.0 in /usr/local/lib/python2.7/dist-packages (from vipermonkey==0.8) (2.3.0)
Requirement already satisfied, skipping upgrade: regex in /usr/local/lib/python2.7/dist-packages (from vipermonkey==0.8) (2019.6.8)
Requirement already satisfied, skipping upgrade: unidecode in /usr/local/lib/python2.7/dist-packages (from vipermonkey==0.8) (1.1.1)
Requirement already satisfied, skipping upgrade: xlrd in /usr/local/lib/python2.7/dist-packages (from vipermonkey==0.8) (1.2.0)
Requirement already satisfied, skipping upgrade: msoffcrypto-tool in /usr/local/lib/python2.7/dist-packages (from oletools->vipermonkey==0.8) (4.10.1)
Requirement already satisfied, skipping upgrade: colorclass in /usr/local/lib/python2.7/dist-packages (from oletools->vipermonkey==0.8) (2.2.0)
Requirement already satisfied, skipping upgrade: easygui in /usr/local/lib/python2.7/dist-packages (from oletools->vipermonkey==0.8) (0.98.1)
Requirement already satisfied, skipping upgrade: cryptography>=2.3 in /usr/lib/python2.7/dist-packages (from msoffcrypto-tool->oletools->vipermonkey==0.8) (2.6.1)
Building wheels for collected packages: vipermonkey
  Running setup.py bdist_wheel for vipermonkey ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-NUkazS/wheels/d7/15/3f/b8e13b6ffef132957c630e9bfd8245761ef842ed66a013054f
Successfully built vipermonkey
Installing collected packages: vipermonkey
  Found existing installation: vipermonkey 0.8
    Uninstalling vipermonkey-0.8:
      Successfully uninstalled vipermonkey-0.8
Successfully installed vipermonkey-0.8

root@malnet:~# vmonkey
Traceback (most recent call last):
  File "/usr/local/bin/vmonkey", line 6, in <module>
    from vipermonkey.vmonkey import main
  File "/usr/local/lib/python2.7/dist-packages/vipermonkey/vmonkey.py", line 126, in <module>
    import core.read_ole_fields as read_ole_fields
  File "/usr/local/lib/python2.7/dist-packages/vipermonkey/core/read_ole_fields.py", line 316
    if ("�            anchor = "�            pad = 3
                                ^
SyntaxError: invalid syntax
```

System information:
```
root@malnet:~# uname -a
Linux malnet 4.19.0-kali5-amd64 #1 SMP Debian 4.19.37-5kali1 (2019-06-20) x86_64 GNU/Linux

root@malnet:~# pip -V
pip 18.1 from /usr/lib/python2.7/dist-packages/pip (python 2.7)

root@malnet:~# python -V
Python 2.7.16
```

**Comment by decalage2** [comment]
There were strings containing non-printable characters. It should now be fixed with commit https://github.com/decalage2/ViperMonkey/commit/edb396b85048aca0db191c91735c8c211b80e708 (in the main repo)
