### ISSUE TITLE
error in _has_constant_loop_guard

### ISSUE THREAD

**Issue by decalage2** [kirk-sayre-work/ViperMonkey#23]
**Describe the bug**
When running vmonkey on [this sample](https://app.any.run/tasks/8436f1cb-e3c5-4d12-ae3b-508222949121/), an error is triggered and stops VBA emulation.

**To Reproduce**
`vmonkey sosp_4923d3e333.doc`

**Output**
```
[...]
-------------------------------------------------------------------------------
TRACING VBA CODE (entrypoint = Auto*):
INFO     Found possible intermediate IOC (URL): 'http://schemas.openxmlformats.org/drawingml/2006/main'
INFO     Emulating loose statements...
INFO     ACTION: Found Entry Point - params 'mstscaxnotsafeforscripting1_onconnecting' -
INFO     evaluating Sub MsTscAxNotSafeForScripting1_OnConnecting
INFO     Calling Procedure: Bikeras("['Application.StartupPath', '\\\\..\\\\..\\\\']")
INFO     calling Function: <vipermonkey.core.vba_library.FreeFile object at 0x03bdf090>()
INFO     ACTION: OPEN - params 'Application.StartupPath\\..\\..\\Gruzzz.ber' - Open File
INFO     Opened file Application.StartupPath/..Gruzzz.ber
INFO     Calling Procedure: Put("['Application.StartupPath\\\\..\\\\..\\\\Gruzzz.ber', '', 'bjbj\\n/*blow23*/;/*autograp...")
INFO     Opened file Application.StartupPath/..Gruzzz.ber
INFO     Calling Procedure: Close("['Application.StartupPath\\\\..\\\\..\\\\Gruzzz.ber']")
INFO     Closing file Application.StartupPath/..Gruzzz.ber
INFO     ACTION: Dropped File Hash - params 'b09665d51520d5a548b8fae58d53834f700f49c7f8351838a8dc3d949fbd177f' - File Name: Application.StartupPath/..Gruzzz.ber
INFO     Wrote dumped file (hash b09665d51520d5a548b8fae58d53834f700f49c7f8351838a8dc3d949fbd177f) to ./sosp_4923d3e333.doc_artifacts/Gruzzz.ber.
WARNING  context.set() Selection.PageSetup.LineNumbering.Active is improper type. <class 'vipermonkey.core.expressions.MemberAccessExpression'>
INFO     Calling Procedure: ImportCSV("['f:\\\\gh.csv']")
INFO     evaluating Sub ImportCSV
INFO     calling Function: Replace('Application.StartupPath\\..\\..\\Gruzzz.ber', '.ber', '.jse')
INFO     calling Function: ulicdr(0, 'WScript.Shell')
INFO     calling Function: CreateObject('WScript.Shell')
INFO     ACTION: CreateObject - params ['WScript.Shell'] - Interesting Function Call
INFO     Explicit exit function invoked
INFO     Calling Procedure: CallByName('[\'WScript.Shell\', \'Run\', 1, \'"Application.StartupPath\\\\..\\\\..\\\\Gruzzz.jse" 578\',...')
INFO     ACTION: Run - params '"Application.StartupPath\\..\\..\\Gruzzz.jse" 578' - Interesting Function Call
INFO     calling Function: Right('f:\\gh.csv', 3)
INFO     calling Function: <vipermonkey.core.vba_library.FreeFile object at 0x03bdf090>()
INFO     ACTION: OPEN - params 'f:\\gh.csv' - Open File
INFO     Opened file f:/gh.csv
Traceback (most recent call last):
  File "c:\ViperMonkey\vipermonkey\vmonkey.py", line 1408, in _process_file
    vm.trace()
  File "c:\ViperMonkey\vipermonkey\core\__init__.py", line 571, in trace
    item.eval(context=context)
  File "c:\ViperMonkey\vipermonkey\core\procedures.py", line 169, in eval
    s.eval(context=context)
  File "c:\ViperMonkey\vipermonkey\core\statements.py", line 3041, in eval
    ret = s.eval(context=context, params=call_params)
  File "c:\ViperMonkey\vipermonkey\core\procedures.py", line 169, in eval
    s.eval(context=context)
  File "c:\ViperMonkey\vipermonkey\core\statements.py", line 2153, in eval
    init_guard_val = self._has_constant_loop_guard(context)
  File "c:\ViperMonkey\vipermonkey\core\statements.py", line 2101, in _has_constant_loop_guard
    self.guard.accept(var_visitor)
AttributeError: 'str' object has no attribute 'accept'
ERROR    'str' object has no attribute 'accept'
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - PyPy 7.1.1 (Python 2.7.13)

**Comment by kirk-sayre-work** [comment]
This is fixed in the most recent version.
